In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline


In [2]:
df = pd.read_csv('Titanic-Dataset.csv')

In [3]:
df.sample(5)

PassengerId  Survived  Pclass  \
617          618         0       3   
846          847         0       3   
152          153         0       3   
273          274         0       1   
8              9         1       3   

                                                  Name     Sex   Age  SibSp  \
617    Lobb, Mrs. William Arthur (Cordelia K Stanlick)  female  26.0      1   
846                           Sage, Mr. Douglas Bullen    male   NaN      8   
152                                   Meo, Mr. Alfonzo    male  55.5      0   
273                              Natsch, Mr. Charles H    male  37.0      0   
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   

     Parch      Ticket     Fare Cabin Embarked  
617      0   A/5. 3336  16.1000   NaN        S  
846      2    CA. 2343  69.5500   NaN        S  
152      0  A.5. 11206   8.0500   NaN        S  
273      1    PC 17596  29.7000  C118        C  
8        2      347742  11.1333   NaN        S

In [4]:
df = df.iloc[:, 1:]
df.sample(5)

Survived  Pclass                                   Name     Sex   Age  \
449         1       1         Peuchen, Major. Arthur Godfrey    male  52.0   
788         1       3             Dean, Master. Bertram Vere    male   1.0   
742         1       1  Ryerson, Miss. Susan Parker "Suzette"  female  21.0   
341         1       1         Fortune, Miss. Alice Elizabeth  female  24.0   
125         1       3           Nicola-Yarred, Master. Elias    male  12.0   

     SibSp  Parch     Ticket      Fare            Cabin Embarked  
449      0      0     113786   30.5000             C104        S  
788      1      2  C.A. 2315   20.5750              NaN        S  
742      2      2   PC 17608  262.3750  B57 B59 B63 B66        C  
341      3      2      19950  263.0000      C23 C25 C27        S  
125      1      0       2651   11.2417              NaN        C

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Survived  891 non-null    int64  
 1   Pclass    891 non-null    int64  
 2   Name      891 non-null    object 
 3   Sex       891 non-null    object 
 4   Age       714 non-null    float64
 5   SibSp     891 non-null    int64  
 6   Parch     891 non-null    int64  
 7   Ticket    891 non-null    object 
 8   Fare      891 non-null    float64
 9   Cabin     204 non-null    object 
 10  Embarked  889 non-null    object 
dtypes: float64(2), int64(4), object(5)
memory usage: 76.7+ KB


In [6]:
X = df.iloc[:, 1:]

In [7]:
X.sample(5)

Pclass                                     Name     Sex   Age  SibSp  \
37        3                 Cann, Mr. Ernest Charles    male  21.0      0   
678       3  Goodwin, Mrs. Frederick (Augusta Tyler)  female  43.0      1   
519       3                      Pavlovic, Mr. Stefo    male  32.0      0   
655       2                Hickman, Mr. Leonard Mark    male  24.0      2   
396       3                      Olsson, Miss. Elina  female  31.0      0   

     Parch        Ticket     Fare Cabin Embarked  
37       0    A./5. 2152   8.0500   NaN        S  
678      6       CA 2144  46.9000   NaN        S  
519      0        349242   7.8958   NaN        S  
655      0  S.O.C. 14879  73.5000   NaN        S  
396      0        350407   7.8542   NaN        S

In [8]:
y = df.iloc[:, 0]

In [9]:
y.sample(5)

110    0
736    0
569    1
312    0
887    1
Name: Survived, dtype: int64

In [10]:
X["Family"] = X['SibSp'] + X['Parch']

In [11]:
X.sample(5)

Pclass                               Name     Sex   Age  SibSp  Parch  \
684       2  Brown, Mr. Thomas William Solomon    male  60.0      1      1   
840       3        Alhomaki, Mr. Ilmari Rudolf    male  20.0      0      0   
266       3          Panula, Mr. Ernesti Arvid    male  16.0      4      1   
517       3                  Ryan, Mr. Patrick    male   NaN      0      0   
796       1        Leader, Dr. Alice (Farnham)  female  49.0      0      0   

               Ticket     Fare Cabin Embarked  Family  
684             29750  39.0000   NaN        S       2  
840  SOTON/O2 3101287   7.9250   NaN        S       0  
266           3101295  39.6875   NaN        S       5  
517            371110  24.1500   NaN        Q       0  
796             17465  25.9292   D17        S       0

In [12]:
X.drop(['SibSp', 'Parch', 'Cabin', 'Ticket', 'Name'], axis = 1, inplace = True)

In [13]:
X.sample(5)

Pclass     Sex   Age     Fare Embarked  Family
131       3    male  20.0   7.0500        S       0
628       3    male  26.0   7.8958        S       0
672       2    male  70.0  10.5000        S       0
479       3  female   2.0  12.2875        S       1
508       3    male  28.0  22.5250        S       0

# Train Test Split

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [15]:
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(712, 6) (179, 6) (712,) (179,)


# Handling Missing Data in Age Column (Using Random Imputation)

In [16]:
X_train['Age_imputed'] = X_train['Age']
X_test['Age_imputed'] = X_test['Age']

In [17]:
X_train['Age_imputed'][X_train['Age_imputed'].isnull()] = X_train['Age'].dropna().sample(X_train['Age'].isnull().sum()).values
X_test['Age_imputed'][X_test['Age_imputed'].isnull()] = X_train['Age'].dropna().sample(X_test['Age'].isnull().sum()).values

C:\Users\PMLS\AppData\Local\Temp\ipykernel_35472\3090101260.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  X_train['Age_imputed'][X_train['Age_imputed'].isnull()] = X_train['Age'].dropna().sample(X_train['Age'].isnull().sum()).values
C:

In [18]:
X_train.drop(['Age'], axis = 1, inplace = True)
X_test.drop(['Age'], axis = 1, inplace = True)

# Handling Missing Data in Embarked Column (Using Most Frequent Imputation)

In [19]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy='most_frequent')

X_train['Embarked'] = imputer.fit_transform(X_train[['Embarked']]).ravel()

X_test['Embarked'] = imputer.transform(X_test[['Embarked']]).ravel()


In [20]:
X_train.sample(5)

Pclass     Sex      Fare Embarked  Family  Age_imputed
146       3    male    7.7958        S       0         27.0
334       1  female  133.6500        S       1         42.0
258       1  female  512.3292        C       0         35.0
856       1  female  164.8667        S       2         45.0
664       3    male    7.9250        S       1         20.0

# Encoding

In [21]:
# encode the categorical columns
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder(drop='first', sparse_output=False, dtype=int)

X_train_sex_embarked = ohe.fit_transform(X_train[['Sex', 'Embarked']])
X_test_sex_embarked = ohe.transform(X_test[['Sex', 'Embarked']])

print(X_train_sex_embarked.shape, X_test_sex_embarked.shape)

(712, 3) (179, 3)


In [22]:
X_train_wo_sex_embarked =  X_train.drop(['Sex', 'Embarked'], axis = 1)
X_test_wo_sex_embarked =  X_test.drop(['Sex', 'Embarked'], axis = 1)

print(X_train_wo_sex_embarked.shape, X_test_wo_sex_embarked.shape)

(712, 4) (179, 4)


In [23]:
X_train_trsm = np.concatenate((X_train_wo_sex_embarked, X_train_sex_embarked), axis = 1)
X_test_trsm = np.concatenate((X_test_wo_sex_embarked, X_test_sex_embarked), axis = 1)

print(X_train_trsm.shape, X_test_trsm.shape)

(712, 7) (179, 7)


In [24]:
X_train_trsm = pd.DataFrame(X_train_trsm)
X_test_trsm = pd.DataFrame(X_test_trsm)

print(X_train_trsm.shape, X_test_trsm.shape)

(712, 7) (179, 7)


# Fit models

### Logistic Regression

In [25]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(X_train_trsm, y_train)

c:\Users\PMLS\anaconda3\envs\traning_env\lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [26]:
y_pred = model.predict(X_test_trsm)

In [27]:
y_pred

array([0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 1], dtype=int64)

In [28]:
# convert y_test to np array
y_test = np.array(y_test)

In [29]:
y_test

array([1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0,
       1, 1, 1], dtype=int64)

In [30]:
from sklearn.metrics import accuracy_score, confusion_matrix

accuracy_score(y_test, y_pred)



0.8044692737430168

In [31]:
confusion_matrix(y_test, y_pred)

array([[90, 15],
       [20, 54]], dtype=int64)

### Random Forest

In [32]:
from sklearn.ensemble import RandomForestClassifier

rfc = RandomForestClassifier(n_estimators=100, random_state=42)
rfc.fit(X_train_trsm, y_train)
y_pred_rfc = rfc.predict(X_test_trsm)

In [33]:
y_pred_rfc

array([0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 1], dtype=int64)

In [34]:
y_test

array([1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0,
       1, 1, 1], dtype=int64)

In [35]:
accuracy_score(y_test, y_pred_rfc)

0.8156424581005587

In [36]:
confusion_matrix(y_test, y_pred_rfc)

array([[89, 16],
       [17, 57]], dtype=int64)