# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` 

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration

In [4]:
print( np.__version__)
print(np.show_config())

1.26.4
{
  "Compilers": {
    "c": {
      "name": "msvc",
      "linker": "link",
      "version": "19.29.30153",
      "commands": "cl"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.0.8",
      "commands": "cython"
    },
    "c++": {
      "name": "msvc",
      "linker": "link",
      "version": "19.29.30153",
      "commands": "cl"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "openblas64",
      "found": true,
      "version": "0.3.23.dev",
      "detection method": "pkgconfig",
      "include directory": "/c/opt/64/include",
      "lib directory": "/c/opt/64/lib",
      "openblas configuration": "USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_

c:\Users\PMLS\anaconda3\envs\traning_env\lib\site-packages\numpy\__config__.py:155: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)


#### 3. Create a null vector of size 10

In [6]:
v = np.zeros(10)
print(v)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array 

In [38]:
v = np.array([100, 20, 34])
print("Memory size of numpy array:",v.size * v.itemsize) 
# v.size will get the size of array and its multiplied with the size of one element to get total memory

Memory size of numpy array: 12


#### 5. How to get the documentation of the numpy add function from the command line?

In [9]:
help(np.add) # to get documentation

# to do so in command line:
"""
first open cmd prompt, then activate your environment, then launch python:

conda activate traning_env
python
import numpy as np
help(np.add)

"""

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

#### 6. Create a null vector of size 10 but the fifth value which is 1

In [10]:
arr = np.zeros(10)
arr[4] = 1
print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49

In [11]:
# np.arange(start, stop) is used to create an array witih a specific range

arr = np.arange(10,50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last)

In [12]:
v = np.array([100, 20, 34]) 
print(v[::-1])

[ 34  20 100]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8

In [13]:
arr = np.arange(9).reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] 

In [15]:
arr = np.array([1,2,0,0,4,0])

print(np.nonzero(arr)) # to get the index of non zero elements

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix

In [17]:
ThreeD = np.eye(3)
print(ThreeD)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values

In [20]:
randarr = np.random.random((3,3,3))
print(randarr)

[[[0.12231791 0.83086794 0.93044118]
  [0.72725649 0.68269459 0.50978986]
  [0.61410219 0.62392357 0.84997682]]

 [[0.37050173 0.56174642 0.16406385]
  [0.30529543 0.8891538  0.62736318]
  [0.6083279  0.7019926  0.28338117]]

 [[0.31730959 0.45783984 0.13963365]
  [0.46463085 0.43759358 0.44768887]
  [0.05398023 0.18449129 0.54510868]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [23]:
arr = np.random.random((10,10))
print(np.min(arr))
print(np.max(arr))

0.013367416729199944
0.9954249248667094


#### 14. Create a random vector of size 30 and find the mean value

In [24]:
arr = np.random.random(30)
print(np.mean(arr))

0.5615864602725175


#### 15. Create a 2d array with 1 on the border and 0 inside

In [29]:
arr = np.ones((10,10))
print(arr)
print()
arr[1:-1,1:-1] = 0   # from 1st to 9th row and 1st to 9th column (-1 is not included)
print(arr)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


```
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
```

#### 16. How to add a border (filled with 0's) around an existing array?

In [32]:
arr = np.ones((5,5))
arr = np.pad(arr, pad_width=1, mode='constant', constant_values=0) # mode = constant is used to fill the array with a specific value
arr

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression?
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [34]:
0 * np.nan

nan

In [35]:
np.nan == np.nan

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [39]:
arr = np.diag([1, 2, 3, 4], k = -1)
print(arr)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [42]:
mat = np.zeros((8,8))
mat[1::2, 0::2] = 1
mat[0::2, 1::2] = 1
print(mat)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 

In [44]:
arr = np.unravel_index(100, (6, 7, 8))
print(arr)

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function

In [49]:
checkBoard = np.tile([[0,1],[1,0]],(4,4)) 
# tile is used to repeat an array. (4,4) means 4 rows and 4 columns. [[0,1],[1,0]] means 0 will be repeated 4 times and 1 will be repeated 4 times
print(checkBoard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix

In [56]:
arr = np.random.rand(5, 5)*10

min_val = arr.min()
max_val = arr.max()

normalized_array = (arr - min_val) / (max_val - min_val)

print(normalized_array)

[[0.79370086 0.31089619 0.5385719  0.2926282  0.00141989]
 [0.15454411 0.72585299 0.         0.83569178 0.53175628]
 [0.59977283 0.54712097 0.42698805 0.8258735  0.3588379 ]
 [0.30306219 0.4288986  0.04542839 0.75007265 0.4898802 ]
 [1.         0.34315357 0.82626598 0.31795367 0.718353  ]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA)

In [84]:
import numpy as np

dtype_rgba = np.dtype([('R', np.uint8), 
                       ('G', np.uint8),
                       ('B', np.uint8),
                       ('A', np.uint8)])

print(dtype_rgba)

[('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')]


In [62]:
# create an array of RGBA colors
colors = np.array([(255, 0, 0, 255),
                   (0, 255, 0, 255),
                   (0, 0, 255, 255)],
                  dtype=dtype_rgba)

print(colors)

[(255,   0,   0, 255) (  0, 255,   0, 255) (  0,   0, 255, 255)]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

In [63]:
mat1 = np.ones((5,3))
mat2 = np.ones((3,2))

print(np.dot(mat1, mat2))

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place.

In [65]:
arr = np.arange(11)
filter = (arr > 3) & (arr < 8) 
arr[filter] *= -1
print(arr)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script?
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [72]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


#### 27. Consider an integer vector Z, which of these expressions are legal?
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [74]:
v = np.array([1,2,3,4,5])

print(v**2)
print(2<< v >>2)
print(v < -v)
print(1j*v)
print(v/1/1)
print(v<v>v)

[ 1  4  9 16 25]
[ 1  2  4  8 16]
[False False False False False]
[0.+1.j 0.+2.j 0.+3.j 0.+4.j 0.+5.j]
[1. 2. 3. 4. 5.]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [75]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

C:\Users\PMLS\AppData\Local\Temp\ipykernel_6636\548293649.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
C:\Users\PMLS\AppData\Local\Temp\ipykernel_6636\548293649.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
C:\Users\PMLS\AppData\Local\Temp\ipykernel_6636\548293649.py:3: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-2.14748365e+09])

#### 29. How to round away from zero a float array ?

In [76]:
arr = np.array([1.1, 2.3, 3.7, 4.5, 5.9])
rounded_up = np.ceil(arr)
rounded_down = np.floor(arr)
print(rounded_up)
print(rounded_down)

[2. 3. 4. 5. 6.]
[1. 2. 3. 4. 5.]


#### 30. How to find common values between two arrays?

In [77]:
arr1 = np.array([1, 2, 3 ,4])
arr2 = np.array([4, 3, 7, 8])

print(np.intersect1d(arr1, arr2))

[3 4]


#### 31. How to ignore all numpy warnings (not recommended)?

In [82]:
np.seterr(all="ignore")

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

In [83]:
# enable again
np.seterr(all="warn")

{'divide': 'ignore', 'over': 'ignore', 'under': 'ignore', 'invalid': 'ignore'}

#### 32. Is the following expressions true?
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [85]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

#### 33. How to get the dates of yesterday, today and tomorrow?

In [87]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')

print("yesterday:", yesterday)
print("today:", today)
print("tomorrow", tomorrow)

yesterday: 2024-07-04
today: 2024-07-05
tomorrow 2024-07-06


#### 34. How to get all the dates corresponding to the month of July 2016?

In [89]:
dates_in_july = np.arange('2016-07', '2016-08', dtype='datetime64[D]') 
print(dates_in_july)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)?

In [93]:
import numpy as np

A = np.array([1, 2, 3], dtype=np.float64)
B = np.array([4, 5, 6])

A += B
A *= (-A / 2)

print(A)

[-12.5 -24.5 -40.5]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods

In [102]:
arr = np.random.uniform(0,10,10)

print(arr - arr % 1)
print(arr // 1)
print(np.floor(arr))
print(arr.astype(int))
print(np.trunc(arr))

[9. 2. 3. 5. 4. 3. 9. 7. 0. 4.]
[9. 2. 3. 5. 4. 3. 9. 7. 0. 4.]
[9. 2. 3. 5. 4. 3. 9. 7. 0. 4.]
[9 2 3 5 4 3 9 7 0 4]
[9. 2. 3. 5. 4. 3. 9. 7. 0. 4.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4

In [106]:
# Create a 5x5 matrix with row values ranging from 0 to 4

arr = np.zeros((5,5))

arr += np.arange(0,5)

print(arr)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array

In [108]:
def generator():
    for i in range(10):
        yield i

arr = np.fromiter(generator(), dtype=np.float64)
print(arr)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded

In [110]:
vec = np.linspace(0, 1, 11, endpoint=False)[1:] #[1:] is used to remove 0 from the array (1st element)

print(vec)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it

In [111]:
vec = np.random.random(10)

vec.sort()

print(vec)

[0.10471668 0.11121684 0.13686721 0.269841   0.27542954 0.28768047
 0.31990172 0.47909208 0.88734344 0.90880057]


#### 41. How to sum a small array faster than np.sum?

In [114]:
arr = [0, 1, 2, 3, 4, 5, 6, 7, 8]
print(sum(arr))

36


#### 42. Consider two random array A and B, check if they are equal

In [115]:
Arr1 = np.random.randint(0,2,5)
Arr2 = np.random.randint(0,2,5)

np.array_equal(Arr1, Arr2)

False

#### 43. Make an array immutable (read-only) 

In [3]:
# Make an array immutable (read-only) 
arr = np.array([1, 2, 3, 4, 5])

arr.flags.writeable = False

arr[0] = 10

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates

In [122]:
cartesian_coords = np.random.rand(10, 2)

x = cartesian_coords[:, 0]
y = cartesian_coords[:, 1]
# radius
r = np.sqrt(x**2 + y**2)
# angle
theta = np.arctan2(y, x)
# angle in degrees
theta_degrees = np.degrees(theta)

polar_coords = np.column_stack((r, theta_degrees))

print("Cartesian Coordinates:\n", cartesian_coords)
print("\nPolar Coordinates (r, theta in degrees):\n", polar_coords)


Cartesian Coordinates:
 [[0.63262207 0.26508687]
 [0.8707758  0.31582601]
 [0.40415451 0.69072207]
 [0.77883566 0.38901778]
 [0.04955491 0.45010193]
 [0.70242172 0.48078148]
 [0.17596017 0.64596836]
 [0.34606642 0.36763827]
 [0.95917792 0.11990187]
 [0.50953514 0.45450993]]

Polar Coordinates (r, theta in degrees):
 [[ 0.68591671 22.73508759]
 [ 0.92628104 19.9354538 ]
 [ 0.8002736  59.66729225]
 [ 0.8705859  26.54150205]
 [ 0.45282163 83.71720555]
 [ 0.85120333 34.39018558]
 [ 0.66950512 74.7624689 ]
 [ 0.5048959  46.73124818]
 [ 0.96664303  7.12528887]
 [ 0.6827923  41.73324892]]


#### 45. Create random vector of size 10 and replace the maximum value by 0

In [123]:
vec = np.random.random(10)

vec[vec.argmax()] = 0

print(vec)

[0.2519718  0.10052623 0.35673567 0.16952589 0.18565119 0.54096192
 0.80170901 0.68669113 0.61779424 0.        ]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area

In [127]:
num_points = 4

grid = np.zeros((num_points*num_points,), dtype=[('x', float), ('y', float)])

# Generate x and y coordinates
x_coords, y_coords = np.meshgrid(np.linspace(0, 1, num_points), np.linspace(0, 1, num_points))

grid['x'] = x_coords.ravel()
grid['y'] = y_coords.ravel()

print(grid)

[(0.        , 0.        ) (0.33333333, 0.        )
 (0.66666667, 0.        ) (1.        , 0.        )
 (0.        , 0.33333333) (0.33333333, 0.33333333)
 (0.66666667, 0.33333333) (1.        , 0.33333333)
 (0.        , 0.66666667) (0.33333333, 0.66666667)
 (0.66666667, 0.66666667) (1.        , 0.66666667)
 (0.        , 1.        ) (0.33333333, 1.        )
 (0.66666667, 1.        ) (1.        , 1.        )]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [128]:
def cauchy_matrix(X, Y):
    m = len(X)
    n = len(Y)
    C = np.zeros((m, n))
    for i in range(m):
        for j in range(n):
            C[i, j] = 1 / (X[i] - Y[j])
    return C

X = np.array([1, 2, 3])
Y = np.array([4, 5])
C = cauchy_matrix(X, Y)
print("Cauchy Matrix C:")
print(C)

Cauchy Matrix C:
[[-0.33333333 -0.25      ]
 [-0.5        -0.33333333]
 [-1.         -0.5       ]]


#### 48. Print the minimum and maximum representable value for each numpy scalar type

In [131]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)

for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? 

In [133]:
np.set_printoptions(threshold=float("inf"))
arr = np.zeros((5,5))
print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector?

In [136]:
arr = np.arange(10)
arr2 = np.random.uniform(0,10)

index = (np.abs(arr-arr2)).argmin()
print(arr[index])

7


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b)

In [140]:
arr = np.zeros(10, [('position', [ ('x', float, 1), ('y', float, 1)]), 
                    ('color', [('r', float, 1), ('g', float, 1), ('b', float, 1)])])

print(arr)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances

In [141]:
vec = np.random.rand(100,2)

x = vec[:, 0]
y = vec[:, 1]

distance = np.sqrt(x**2 + y**2)

print(distance)

[1.13428241 0.25402117 0.67357987 0.4823674  0.66803886 0.92376952
 1.27478538 0.71781876 1.05389318 0.48638911 1.06097079 1.26111613
 0.99535778 0.30487767 0.98152737 0.51363968 1.18400552 0.96401288
 0.85358408 0.9654937  1.15018033 1.25348441 0.43809295 0.9353613
 0.92725982 0.76658473 0.62737457 1.03405008 1.15496913 1.20596921
 0.84960767 1.20050927 0.86944256 0.60043593 0.51670649 0.93684468
 0.80248974 0.16526095 0.61344425 1.27444113 1.22411863 0.79569033
 0.95058497 0.75964362 0.92801918 0.65457826 1.12707435 0.48402598
 0.89684831 0.76811188 0.14948694 1.0223736  0.92643478 1.14598307
 1.38445013 1.23524736 0.71991091 0.96663182 1.09199139 0.86431052
 1.04106348 0.60582822 0.77572422 0.73428101 0.71621448 1.12632697
 0.59340834 0.96251489 0.6260469  0.64189338 0.3593716  0.57477242
 0.91088645 1.22526837 0.50379827 0.62667901 0.70447458 0.87529561
 0.61826441 0.97053851 1.18936942 1.0431334  1.15033563 0.47316533
 0.95011803 0.88176692 0.21990532 0.56705953 1.1400174  0.40840

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [145]:
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


#### 54. How to read the following file?
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [7]:
from io import StringIO

# Fake file
s = StringIO('''1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11
''')

arr = np.genfromtxt(s, delimiter=",", dtype=np.int64)
print(arr)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays?

In [146]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for index, value in np.ndenumerate(arr):
    print(index, value)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6


#### 56. Generate a generic 2D Gaussian-like array

In [15]:
X, Y = np.meshgrid(np.linspace(-1,1,5), 
                   np.linspace(-1,1,5))

D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )

print(G)

[[0.36787944 0.53526143 0.60653066 0.53526143 0.36787944]
 [0.53526143 0.77880078 0.8824969  0.77880078 0.53526143]
 [0.60653066 0.8824969  1.         0.8824969  0.60653066]
 [0.53526143 0.77880078 0.8824969  0.77880078 0.53526143]
 [0.36787944 0.53526143 0.60653066 0.53526143 0.36787944]]


#### 57. How to randomly place p elements in a 2D array?

In [21]:
arr = np.zeros((5,5))
p = 8
n = 4
np.put(arr, np.random.choice(range(5*5), p, replace=False), n)
print(arr)

[[0. 0. 0. 0. 4.]
 [4. 0. 4. 0. 0.]
 [0. 0. 0. 0. 4.]
 [4. 4. 0. 0. 0.]
 [0. 0. 4. 0. 4.]]


#### 58. Subtract the mean of each row of a matrix

In [22]:
arr = np.random.rand(3,3)
arr_mean = arr.mean(axis=1, keepdims=True)
sub_mean = arr - arr_mean

print(sub_mean)

[[ 0.27866241  0.22564637 -0.50430878]
 [-0.29915748  0.04277744  0.25638004]
 [-0.01073789 -0.05519289  0.06593078]]


#### 59. How to sort an array by the nth column?

In [28]:
arr = np.array([[1, 3, 4, 2], [3, 6, 9, 7], [2, 5, 8, 1]])
n = 1 # 1st column
ncol_sort = arr[arr[:, n].argsort()]
print(arr)
print(ncol_sort)

[[1 3 4 2]
 [3 6 9 7]
 [2 5 8 1]]
[[1 3 4 2]
 [2 5 8 1]
 [3 6 9 7]]


#### 60. How to tell if a given 2D array has null columns?

In [30]:
arr = np.array([[0, 2, 0],
                [0, 0, 0],
                [0, 8, 0]])

null_col = np.all(arr == 0, axis=0)

null_col_ind = np.where(null_col)[0]

print(arr)
print(f"Index of Null columns: {null_col_ind}")

[[0 2 0]
 [0 0 0]
 [0 8 0]]
Index of Null columns: [0 2]


#### 61. Find the nearest value from a given value in an array

In [39]:
arr = np.array([1, 2, 3, 4, 5])

val = 3.6

index = np.abs(arr - val).argmin() 
# np.abs(arr - val) will calculate the absolute difference of the value from each element in the array
# .argmin() will get the index of the value with the smallest difference

print(arr[index])

4


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator?

In [51]:
arr1 = np.arange(3).reshape(1,3)
arr2 = np.arange(3).reshape(3,1)

iterat = np.nditer([arr1, arr2, None])
for x,y,z in iterat: 
    z[...] = x + y

print(iterat.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute

In [52]:
class MyArray(np.ndarray):
    def __new__(cls, array, name="MyArray"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj

    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "MyArray")

arr = np.arange(10)
myarr = MyArray(arr)
print(myarr.name)

MyArray


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

In [57]:
vec1 = np.ones(10)
vec2 = np.random.randint(0,len(vec1),20)
np.add.at(vec1, vec2, 1)

print(vec1)

[3. 5. 3. 2. 4. 2. 1. 4. 2. 4.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)?

In [58]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]

F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors

In [60]:
w, h = 256, 256
Img = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(Img.reshape(-1, 3), axis=0)

print(len(colors))

64


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once?

In [65]:
arr = np.random.rand(2, 2, 2, 2)

sums = arr.sum(axis=(-2,-1))

print(sums)

[[1.84452644 2.17501302]
 [1.91361861 1.9693392 ]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices?

In [67]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)

D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)

D_means = D_sums / D_counts
print(D_means)

[0.31030285 0.35387346 0.45333845 0.73054711 0.29586504 0.42106519
 0.56413864 0.53151763 0.29270558 0.4851407 ]


#### 69. How to get the diagonal of a dot product?

In [73]:
arr1 = np.random.uniform(0,1,(5,5))
arr2 = np.random.uniform(0,1,(5,5))
dot_product = np.dot(arr1, arr2)
diagonal_dot_product = np.diag(dot_product)

print(dot_product)
print()
print(diagonal_dot_product)

[[1.58085029 0.92340111 1.42518899 1.23502615 0.84868561]
 [1.88048977 1.29288533 1.68661184 1.56283238 1.23186225]
 [0.62942773 0.93915481 0.71462783 0.65932494 1.07628889]
 [0.98970948 0.61173474 0.977141   0.78574699 0.60709785]
 [1.360757   1.17341975 1.3098011  1.3546264  1.57724915]]

[1.58085029 1.29288533 0.71462783 0.78574699 1.57724915]


#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value?

In [78]:
original_vector = np.array([1, 2, 3, 4, 5])

num_zeros = 3

new_length = len(original_vector) + (len(original_vector) - 1) * num_zeros 
new_vector = np.zeros(new_length, dtype=int)

new_vector[::num_zeros + 1] = original_vector  # for num_zeros = 3, new_vector[::4] means selcting every 4th element

print(new_vector)


[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)?

In [3]:
arr = np.random.rand(5, 5, 3)
arr2 = np.random.rand(5, 5)

arr_multiplied = arr * arr2[:, :, np.newaxis] # this line means that arr2[:, :, np.newaxis] will be added to each element of arr. 
# this is called broadcasting method, in which the shape of the result will be the same as the shape of the operands

print(arr_multiplied)

[[[0.07351869 0.44394764 0.58468946]
  [0.33231224 0.20369492 0.19655903]
  [0.62155444 0.14513221 0.41549726]
  [0.53045342 0.76801808 0.33355653]
  [0.14891428 0.89153297 0.58066119]]

 [[0.3694317  0.25058202 0.04729422]
  [0.00377583 0.00721153 0.00712131]
  [0.12139685 0.01393851 0.05766396]
  [0.40413868 0.19011821 0.15031164]
  [0.14527557 0.13777807 0.10337746]]

 [[0.09744791 0.07260453 0.01770412]
  [0.18188687 0.11256587 0.01440722]
  [0.02653395 0.35197942 0.2569885 ]
  [0.10028183 0.07906342 0.08635031]
  [0.67573165 0.8861217  0.24996209]]

 [[0.21053857 0.43702559 0.04655147]
  [0.39127228 0.24853728 0.89448752]
  [0.55076222 0.43800408 0.12557536]
  [0.1466998  0.53006206 0.10759245]
  [0.498554   0.83524805 0.31286197]]

 [[0.08978788 0.44948765 0.26379588]
  [0.03695874 0.10125432 0.01376308]
  [0.01456427 0.65185318 0.48777124]
  [0.25754768 0.63324818 0.04718517]
  [0.50355122 0.075726   0.52946415]]]


#### 72. How to swap two rows of an array?

In [5]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

arr[[1, 2]] = arr[[2, 1]]

print(arr)

[[1 2 3]
 [7 8 9]
 [4 5 6]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C?

In [6]:
C = np.bincount([1, 1, 2, 3, 4, 4, 6])
A = np.repeat(np.arange(len(C)), C)

print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array?

In [8]:
def sliding_window_average(arr, k):
    # Pad the array
    cumsum = np.cumsum(arr)
    cumsum[k:] = cumsum[k:] - cumsum[:-k]
    
    # sliding window average
    averages = cumsum[k - 1:] / k
    return averages

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
k = 3  

result = sliding_window_average(arr, k)
print(result)

[2. 3. 4. 5. 6. 7. 8. 9.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1])

In [4]:
Z = np.array([1, 2, 3, 4, 5, 6, 7])

n_cols = 3  # Since each row has 3 elements

# Compute the number of rows needed
n_rows = len(Z) - n_cols + 1

result = np.array([Z[i:i+n_cols] for i in range(n_rows)])

print(result)

[[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]]


#### 77. How to negate a boolean, or to change the sign of a float inplace?

In [7]:
arr1 = np.random.randint(0,2,10)
print(np.logical_not(arr1, out=arr1))

arr2 = np.random.uniform(-1.0,1.0,10)
print(np.negative(arr2, out=arr2))

[1 0 0 1 0 0 1 0 0 1]
[ 0.30316718 -0.97083104 -0.30029864  0.59833317 -0.24622687 -0.12825525
 -0.17903656  0.73023704  0.19501085 -0.35468501]


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])?

In [8]:
def distance_point_to_line(P0, P1, p):
    x0, y0 = p[...,0], p[..., 1]
    
    x1, y1 = P0[:, 0], P0[:, 1]
    x2, y2 = P1[:, 0], P1[:, 1]

    numerator = np.abs((y2 - y1) * x0 - (x2 - x1) * y0 + x2 * y1 - y2 * x1)
    denominator = np.sqrt((y2 - y1)**2 + (x2 - x1)**2)
    distance = numerator / denominator
    
    return distance
P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))

distances = distance_point_to_line(P0, P1, p)
print(distances)

[ 6.82042885  1.3823253   0.43536665  7.73228897  2.41682313 13.73832223
  7.80216586  5.36955531  8.91433164  1.60578998]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])?

In [9]:
# using the function from above problem
P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,(10,2))

distances = [distance_point_to_line(P0,P1,x) for x in p] 

print(distances)

[array([ 6.71828608,  3.47919853,  1.80176239,  6.86814367,  5.48347593,
        2.06389021,  8.61194333,  3.34806896, 13.57498791,  4.32577985]), array([ 2.21658658,  0.76743069,  5.83800416,  1.55830507,  6.36188035,
        3.36427173,  7.21297565,  0.97804084, 12.04908779,  1.04338665]), array([10.35505225,  7.42317462,  2.36454388,  5.06184047,  0.22323573,
        3.87584447,  3.09198202,  7.20115244,  8.09385401,  6.32646711]), array([6.0823422 , 3.30848524, 1.61471845, 1.0206239 , 1.42901659,
       0.85469561, 2.85347997, 3.03643145, 7.74531317, 1.6131999 ]), array([12.97800415, 10.10006275,  5.07366117,  5.74999369,  2.70706557,
        6.02310645,  1.28272723,  9.86314189,  6.33341256,  8.53264391]), array([ 6.14595755,  9.20401758, 14.302506  ,  1.79860869, 13.32757276,
       10.70111863, 11.71261873,  9.39671655, 16.38094792,  8.52296977]), array([9.94352216, 7.38675145, 2.61622674, 0.3983679 , 3.56785943,
       1.61593997, 1.59381372, 7.05115867, 3.35278393, 4.23397629]

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?

In [16]:
Z = np.arange(0,15)

n_cols = 4 

# Compute the number of rows needed
n_rows = len(Z) - n_cols + 1

result = np.array([Z[i:i+n_cols] for i in range(n_rows)])


print(result[1:])

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [19]:
Z = np.random.uniform(0,10,(10,10))
rank = np.linalg.matrix_rank(Z)
print(rank), Z

10


(None,
 array([[3.88870805, 6.72430796, 4.74455488, 7.65688205, 4.417793  ,
         3.61341736, 1.6887811 , 5.05267067, 1.47071419, 8.67369689],
        [1.20818072, 1.19661278, 3.72398425, 1.60015826, 2.80973775,
         5.74999526, 1.98780169, 6.01678095, 9.36685807, 6.63362647],
        [1.52395826, 9.5056831 , 9.94897287, 9.33953534, 0.39605395,
         9.26265524, 4.32424003, 3.50594846, 1.74890223, 5.7529843 ],
        [4.57261372, 9.54393534, 3.48049202, 8.73709749, 5.92790218,
         7.24133476, 1.60647494, 6.28776872, 0.99603695, 3.36430075],
        [1.98679483, 5.24323052, 6.61361021, 6.33470893, 4.26737362,
         5.94126023, 5.65539096, 6.92133349, 7.01316512, 1.10908403],
        [7.15775768, 7.06930222, 5.63897265, 6.42524048, 7.13504845,
         3.53277798, 5.62083982, 5.5969362 , 8.9830979 , 5.52974373],
        [4.66526836, 7.06566369, 0.23289384, 3.35958874, 2.68249293,
         1.23987227, 8.00769465, 8.2289483 , 5.78856921, 3.22683844],
        [1.69568377,

#### 83. How to find the most frequent value in an array?

In [20]:
arr = np.array([1, 2, 3, 2, 2, 3, 1, 3, 3, 3])
most_frequent_value = np.bincount(arr).argmax()
print(most_frequent_value)

3


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix

In [21]:
from numpy.lib.stride_tricks import sliding_window_view

Z = np.random.randint(0,5,(10,10))
print(sliding_window_view(Z, window_shape=(3, 3)))

[[[[4 1 4]
   [2 1 1]
   [0 0 0]]

  [[1 4 0]
   [1 1 2]
   [0 0 3]]

  [[4 0 1]
   [1 2 0]
   [0 3 1]]

  [[0 1 4]
   [2 0 3]
   [3 1 3]]

  [[1 4 3]
   [0 3 4]
   [1 3 1]]

  [[4 3 3]
   [3 4 0]
   [3 1 2]]

  [[3 3 4]
   [4 0 2]
   [1 2 4]]

  [[3 4 3]
   [0 2 4]
   [2 4 2]]]


 [[[2 1 1]
   [0 0 0]
   [4 2 1]]

  [[1 1 2]
   [0 0 3]
   [2 1 2]]

  [[1 2 0]
   [0 3 1]
   [1 2 2]]

  [[2 0 3]
   [3 1 3]
   [2 2 1]]

  [[0 3 4]
   [1 3 1]
   [2 1 1]]

  [[3 4 0]
   [3 1 2]
   [1 1 3]]

  [[4 0 2]
   [1 2 4]
   [1 3 4]]

  [[0 2 4]
   [2 4 2]
   [3 4 2]]]


 [[[0 0 0]
   [4 2 1]
   [3 0 4]]

  [[0 0 3]
   [2 1 2]
   [0 4 4]]

  [[0 3 1]
   [1 2 2]
   [4 4 4]]

  [[3 1 3]
   [2 2 1]
   [4 4 4]]

  [[1 3 1]
   [2 1 1]
   [4 4 0]]

  [[3 1 2]
   [1 1 3]
   [4 0 4]]

  [[1 2 4]
   [1 3 4]
   [0 4 1]]

  [[2 4 2]
   [3 4 2]
   [4 1 1]]]


 [[[4 2 1]
   [3 0 4]
   [4 0 4]]

  [[2 1 2]
   [0 4 4]
   [0 4 1]]

  [[1 2 2]
   [4 4 4]
   [4 1 4]]

  [[2 2 1]
   [4 4 4]
   [1 4 3]]

  [[2 1 1]
   

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i]

In [23]:
class SymmetricArray:
    def __init__(self, size):
        self.size = size
        self.data = [[0] * size for _ in range(size)]

    def __getitem__(self, indices):
        i, j = indices
        return self.data[i][j]

    def __setitem__(self, indices, value):
        i, j = indices
        self.data[i][j] = value
        self.data[j][i] = value

size = 3
Z = SymmetricArray(size)

Z[0, 1] = 10
print(Z[1, 0])

10


#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1))

In [24]:
p = 5
n = 3

matrices = [np.random.rand(n, n) for _ in range(p)]
vectors = [np.random.rand(n, 1) for _ in range(p)]

result = np.sum(np.matmul(matrices[i], vectors[i]) for i in range(p))

print(result)

[[3.12166731]
 [3.42934784]
 [5.13488137]]


C:\Users\PMLS\AppData\Local\Temp\ipykernel_10124\3810731232.py:7: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  result = np.sum(np.matmul(matrices[i], vectors[i]) for i in range(p))


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? 

#### 88. How to implement the Game of Life using numpy arrays?

#### 89. How to get the n largest values of an array

In [32]:
arr = np.arange(10000)
np.random.shuffle(arr)
n = 5

indices = np.argpartition(arr, -n)[-n:]

largest_values = arr[indices]
print(largest_values)

[9995 9996 9997 9999 9998]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) 

#### 91. How to create a record array from a regular array?

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B?

In [40]:
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9],
              [3, 1, 2],
              [6, 4, 5],
              [9, 7, 8],
              [2, 3, 1],
              [5, 6, 4]])

B = np.array([[1, 2],
              [4, 5]])

result_rows = []
for row in A:
    for b_row in B:
        if all(element in row for element in b_row):
            result_rows.append(row)
            break

result_rows_of_A = np.array(result_rows)

print("Array A:")
print(A)
print("\nArray B:")
print(B)
print("\nRows of A containing elements of each row of B (regardless of order):")
print(result_rows_of_A)


Array A:
[[1 2 3]
 [4 5 6]
 [7 8 9]
 ...
 [9 7 8]
 [2 3 1]
 [5 6 4]]

Array B:
[[1 2]
 [4 5]]

Rows of A containing elements of each row of B (regardless of order):
[[1 2 3]
 [4 5 6]
 [3 1 2]
 [6 4 5]
 [2 3 1]
 [5 6 4]]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3])

In [41]:
arr = np.random.randint(0,5,(10,3))
output = arr[np.apply_along_axis(lambda row: len(set(row)) == len(row), 1, arr)]
arr, output

(array([[4, 1, 0],
        [2, 3, 3],
        [2, 2, 2],
        ...,
        [1, 4, 4],
        [1, 3, 0],
        [0, 1, 4]]),
 array([[4, 1, 0],
        [2, 3, 0],
        [1, 3, 4],
        [1, 3, 0],
        [0, 1, 4]]))

#### 95. Convert a vector of ints into a matrix binary representation

#### 96. Given a two dimensional array, how to extract unique rows?

In [43]:
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [1, 2, 3],
                  [7, 8, 9],
                  [4, 5, 6]])
unique_rows = np.unique(array, axis=0)
unique_rows

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function

In [44]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

sum_A = np.einsum('i->', A)
print("Sum of elements of A:", sum_A)

elementwise_multiplication = np.einsum('i,i->i', A, B)
print("Element-wise multiplication:", elementwise_multiplication)

inner_product = np.einsum('i,i', A, B)
print("Inner product:", inner_product)

outer_product = np.einsum('i,j->ij', A, B)
print("Outer product:\n", outer_product)

Sum of elements of A: 5.808074964716228
Element-wise multiplication: [0.0575917  0.30152033 0.14139266 0.51945636 0.48995243 0.2567764
 0.74106744 0.12256495 0.27195054 0.08611   ]
Inner product: 2.988382800616216
Outer product:
 [[0.0575917  0.22406599 0.33795377 0.39978969 0.28585418 0.47472541
  0.5182032  0.1186856  0.27419888 0.13993272]
 [0.0774998  0.30152033 0.45477644 0.53798759 0.38466724 0.63882681
  0.69733386 0.15971242 0.36898299 0.18830417]
 [0.02409514 0.09374444 0.14139266 0.16726349 0.1195953  0.19861499
  0.21680518 0.04965553 0.11471897 0.05854487]
 [0.07483028 0.29113433 0.43911146 0.51945636 0.37141721 0.61682214
  0.67331388 0.15421105 0.3562732  0.18181795]
 [0.09871184 0.38404782 0.57925083 0.68523725 0.48995243 0.81367663
  0.88819733 0.20342644 0.46997532 0.23984389]
 [0.03115104 0.12119608 0.18279736 0.21624408 0.15461697 0.2567764
  0.2802933  0.0641964  0.14831269 0.07568885]
 [0.08236023 0.3204303  0.48329793 0.5717277  0.40879181 0.6788911
  0.74106744 0

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n.

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means).